name: Trade Block Bug
description: Report a bug affecting Trade Block.
title: "[Trade Block Bug]: "
labels:
  - "Trade Block: bug"
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the bug.
      placeholder: "What went wrong?"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions to trigger the bug.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: Environment
      description: Browser / device / app version, etc.
      placeholder: "e.g. Chrome on Windows, iPhone / iOS"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / recordings
      description: Drag and drop any images or screen recordings that show the issue.
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Any other details, logs, or notes.
    validations:
      required: false
